<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class Szekeny_Seeder extends Seeder
{
    public function run(){
        DB::table('szekenies')->insert([
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'F','tipusa' => 'Férfi'],
            ['ures_e' => 'F','tipusa' => 'Férfi'],
            ['ures_e' => 'F','tipusa' => 'Férfi'],
            ['ures_e' => 'F','tipusa' => 'Férfi'],
            ['ures_e' => 'F','tipusa' => 'Férfi'],
            ['ures_e' => 'F','tipusa' => 'Férfi'],
            ['ures_e' => 'F','tipusa' => 'Férfi'],
            ['ures_e' => 'F','tipusa' => 'Férfi'],
            ['ures_e' => 'F','tipusa' => 'Férfi'],
            ['ures_e' => 'R','tipusa' => 'Férfi'],
            ['ures_e' => 'R','tipusa' => 'Férfi'],
            ['ures_e' => 'R','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Férfi'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'Ü','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő'],
            ['ures_e' => 'F','tipusa' => 'Nő']
	]);
    }
}